# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pnoj4dHmI_QNH1OvcVW_vB1jfNmKKc8x
"""

import numpy as np
import matplotlib.pyplot as plt

# Sinus funksiyasi uchun grafik
x = np.linspace(0, 10, 100)
y = np.sin(x)

plt.figure(figsize=(12, 6))

# Chap grafik
plt.subplot(1, 2, 1)
plt.plot(x, y, label='Sinus(x)', color='blue')
plt.title('Sinus Funksiyasining Grafik')
plt.xlabel('X qiymatlari')
plt.ylabel('Y qiymatlari')
plt.legend()
plt.grid(True)

# Tasodifiy nuqtalar uchun scatter grafik
np.random.seed(42)
x_random = np.random.uniform(0, 10, 50)
y_random = np.random.uniform(0, 10, 50)

plt.subplot(1, 2, 2)
plt.scatter(x_random, y_random, color='blue', label='Nuqtalar')
plt.title('Tasodifiy Nuqtalar Scatter Grafik')
plt.xlabel('X qiymatlari')
plt.ylabel('Y qiymatlari')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()